[project]
name = "ms-bart"
version = "0.1.0"
requires-python = ">=3.9,<3.10"
dependencies = [
    "accelerate==1.5.1",
    "cairosvg==2.7.1",
    "datasets==3.3.2",
    "h5py==3.12.1",
    "jsonlines==4.0.0",
    "matchms==0.8.1",
    "matplotlib==3.9.2",
    "myopic-mces==1.0.1",
    "numpy==1.23.5",
    "pandas==2.2.2",
    "pathos==0.3.2",
    "pebble==5.1.0",
    "psutil==6.0.0",
    "pulp==3.0.2",
    "pyteomics==4.7.5",
    "pytorch-lightning==1.9.5",
    "ray[tune]==2.40.0",
    "rdkit==2024.9.5",
    "rich==14.0.0",
    "seaborn==0.13.2",
    "selfies==2.2.0",
    "setuptools==80.9.0",
    "torch==2.6.0",
    "tqdm==4.66.5",
    "transformers==4.49.0",
    "trl==0.16.1",
    "wandb==0.19.7",
]

[tool.uv]
package = false
